<?php

declare(strict_types=1);

/*
 * This file is part of the Modelflow AI package.
 *
 * (c) Johannes Wachter <johannes@sulu.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace ModelflowAi\Integration\Symfony\Configuration;

use ModelflowAi\DecisionTree\Criteria\CapabilityCriteria;
use ModelflowAi\DecisionTree\Criteria\CriteriaInterface;
use ModelflowAi\Integration\Symfony\Criteria\ModelCriteria;
use ModelflowAi\Integration\Symfony\Criteria\ProviderCriteria;

final readonly class DefaultConfigurationProvider
{
    /**
     * @return array<string, array{
     *     provider: string,
     *     model: string,
     *     chat: bool,
     *     completion: bool,
     *     stream: bool,
     *     tools: bool,
     *     image_to_text: bool,
     *     text_to_image: bool,
     *     criteria: CriteriaInterface[],
     * }>
     */
    public static function getDefaultValues(): array
    {
        return [
            'gpt4o_mini' => [
                'provider' => ProviderCriteria::OPENAI->value,
                'model' => ModelCriteria::GPT4O_MINI->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => true,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::GPT4O_MINI,
                    ProviderCriteria::OPENAI,
                    CapabilityCriteria::INTERMEDIATE,
                ],
            ],
            'gpt4o' => [
                'provider' => ProviderCriteria::OPENAI->value,
                'model' => ModelCriteria::GPT4O->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => true,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::GPT4O,
                    ProviderCriteria::OPENAI,
                    CapabilityCriteria::SMART,
                ],
            ],
            'gpt4' => [
                'provider' => ProviderCriteria::OPENAI->value,
                'model' => ModelCriteria::GPT4->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => true,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::GPT4,
                    ProviderCriteria::OPENAI,
                    CapabilityCriteria::SMART,
                ],
            ],
            'gpt3.5' => [
                'provider' => ProviderCriteria::OPENAI->value,
                'model' => ModelCriteria::GPT3_5->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => true,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::GPT3_5,
                    ProviderCriteria::OPENAI,
                    CapabilityCriteria::INTERMEDIATE,
                ],
            ],
            'dall_e_3' => [
                'provider' => ProviderCriteria::OPENAI->value,
                'model' => ModelCriteria::DALL_E_3->value,
                'chat' => false,
                'completion' => false,
                'stream' => false,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => true,
                'criteria' => [
                    ModelCriteria::DALL_E_3,
                    ProviderCriteria::OPENAI,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'dall_e_2' => [
                'provider' => ProviderCriteria::OPENAI->value,
                'model' => ModelCriteria::DALL_E_2->value,
                'chat' => false,
                'completion' => false,
                'stream' => false,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => true,
                'criteria' => [
                    ModelCriteria::DALL_E_2,
                    ProviderCriteria::OPENAI,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'mistral_tiny' => [
                'provider' => ProviderCriteria::MISTRAL->value,
                'model' => ModelCriteria::MISTRAL_TINY->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::MISTRAL_TINY,
                    ProviderCriteria::MISTRAL,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'mistral_small' => [
                'provider' => ProviderCriteria::MISTRAL->value,
                'model' => ModelCriteria::MISTRAL_SMALL->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::MISTRAL_SMALL,
                    ProviderCriteria::MISTRAL,
                    CapabilityCriteria::INTERMEDIATE,
                ],
            ],
            'mistral_medium' => [
                'provider' => ProviderCriteria::MISTRAL->value,
                'model' => ModelCriteria::MISTRAL_MEDIUM->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::MISTRAL_MEDIUM,
                    ProviderCriteria::MISTRAL,
                    CapabilityCriteria::ADVANCED,
                ],
            ],
            'mistral_nemo' => [
                'provider' => ProviderCriteria::MISTRAL->value,
                'model' => ModelCriteria::MISTRAL_NEMO->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => true,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::MISTRAL_NEMO,
                    ProviderCriteria::MISTRAL,
                    CapabilityCriteria::INTERMEDIATE,
                ],
            ],
            'mistral_large' => [
                'provider' => ProviderCriteria::MISTRAL->value,
                'model' => ModelCriteria::MISTRAL_LARGE->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => true,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::MISTRAL_LARGE,
                    ProviderCriteria::MISTRAL,
                    CapabilityCriteria::SMART,
                ],
            ],
            'pixtral_large' => [
                'provider' => ProviderCriteria::MISTRAL->value,
                'model' => ModelCriteria::PIXTRAL_LARGE->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::PIXTRAL_LARGE,
                    ProviderCriteria::MISTRAL,
                    CapabilityCriteria::SMART,
                ],
            ],
            'llama2' => [
                'provider' => ProviderCriteria::OLLAMA->value,
                'model' => ModelCriteria::LLAMA2->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::LLAMA2,
                    ProviderCriteria::OLLAMA,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'llama3' => [
                'provider' => ProviderCriteria::OLLAMA->value,
                'model' => ModelCriteria::LLAMA3->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::LLAMA3,
                    ProviderCriteria::OLLAMA,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'llama3_2' => [
                'provider' => ProviderCriteria::OLLAMA->value,
                'model' => ModelCriteria::LLAMA3_2->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::LLAMA3_2,
                    ProviderCriteria::OLLAMA,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'nexusraven' => [
                'provider' => ProviderCriteria::OLLAMA->value,
                'model' => ModelCriteria::NEXUSRAVEN->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::NEXUSRAVEN,
                    ProviderCriteria::OLLAMA,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'llava' => [
                'provider' => ProviderCriteria::OLLAMA->value,
                'model' => ModelCriteria::LLAVA->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::LLAVA,
                    ProviderCriteria::OLLAMA,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'claude_3_5_sonnet' => [
                'provider' => ProviderCriteria::ANTHROPIC->value,
                'model' => ModelCriteria::CLAUDE_3_5_SONNET->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::CLAUDE_3_5_SONNET,
                    ProviderCriteria::ANTHROPIC,
                    CapabilityCriteria::SMART,
                ],
            ],
            'claude_3_opus' => [
                'provider' => ProviderCriteria::ANTHROPIC->value,
                'model' => ModelCriteria::CLAUDE_3_OPUS->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::CLAUDE_3_OPUS,
                    ProviderCriteria::ANTHROPIC,
                    CapabilityCriteria::SMART,
                ],
            ],
            'claude_3_sonnet' => [
                'provider' => ProviderCriteria::ANTHROPIC->value,
                'model' => ModelCriteria::CLAUDE_3_SONNET->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::CLAUDE_3_SONNET,
                    ProviderCriteria::ANTHROPIC,
                    CapabilityCriteria::ADVANCED,
                ],
            ],
            'claude_3_5_haiku' => [
                'provider' => ProviderCriteria::ANTHROPIC->value,
                'model' => ModelCriteria::CLAUDE_3_5_HAIKU->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::CLAUDE_3_5_HAIKU,
                    ProviderCriteria::ANTHROPIC,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'claude_3_haiku' => [
                'provider' => ProviderCriteria::ANTHROPIC->value,
                'model' => ModelCriteria::CLAUDE_3_HAIKU->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::CLAUDE_3_HAIKU,
                    ProviderCriteria::ANTHROPIC,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'fireworksai_llama3_1_405b' => [
                'provider' => ProviderCriteria::FIREWORKSAI->value,
                'model' => ModelCriteria::LLAMA3_1_405B_FIREWORKS->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::LLAMA3_1_405B_FIREWORKS,
                    ProviderCriteria::FIREWORKSAI,
                    CapabilityCriteria::SMART,
                ],
            ],
            'fireworksai_llama3_1_70b' => [
                'provider' => ProviderCriteria::FIREWORKSAI->value,
                'model' => ModelCriteria::LLAMA3_1_70B_FIREWORKS->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::LLAMA3_1_70B_FIREWORKS,
                    ProviderCriteria::FIREWORKSAI,
                    CapabilityCriteria::INTERMEDIATE,
                ],
            ],
            'fireworksai_llama3_1_8b' => [
                'provider' => ProviderCriteria::FIREWORKSAI->value,
                'model' => ModelCriteria::LLAMA3_1_8B_FIREWORKS->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::LLAMA3_1_8B_FIREWORKS,
                    ProviderCriteria::FIREWORKSAI,
                    CapabilityCriteria::INTERMEDIATE,
                ],
            ],
            'fireworksai_llama3_70b' => [
                'provider' => ProviderCriteria::FIREWORKSAI->value,
                'model' => ModelCriteria::LLAMA3_70B_FIREWORKS->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::LLAMA3_70B_FIREWORKS,
                    ProviderCriteria::FIREWORKSAI,
                    CapabilityCriteria::INTERMEDIATE,
                ],
            ],
            'fireworksai_mixtral' => [
                'provider' => ProviderCriteria::FIREWORKSAI->value,
                'model' => ModelCriteria::MIXTRAL_FIREWORKS->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::MIXTRAL_FIREWORKS,
                    ProviderCriteria::FIREWORKSAI,
                    CapabilityCriteria::ADVANCED,
                ],
            ],
            'fireworksai_firefunction_v2' => [
                'provider' => ProviderCriteria::FIREWORKSAI->value,
                'model' => ModelCriteria::FIREFUNCTION_V2_FIREWORKS->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => true,
                'image_to_text' => false,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::FIREFUNCTION_V2_FIREWORKS,
                    ProviderCriteria::FIREWORKSAI,
                    CapabilityCriteria::INTERMEDIATE,
                ],
            ],
            'fireworksai_llava_13b' => [
                'provider' => ProviderCriteria::FIREWORKSAI->value,
                'model' => ModelCriteria::LLAVA_13B_FIREWORKS->value,
                'chat' => true,
                'completion' => true,
                'stream' => true,
                'tools' => false,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::LLAVA_13B_FIREWORKS,
                    ProviderCriteria::FIREWORKSAI,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'stable_diffusion_xl_fireworks' => [
                'provider' => ProviderCriteria::FIREWORKSAI->value,
                'model' => ModelCriteria::STABLE_DIFFUSSION_XL_1024_FIREWORKS->value,
                'chat' => false,
                'completion' => false,
                'stream' => false,
                'tools' => false,
                'image_to_text' => false,
                'text_to_image' => true,
                'criteria' => [
                    ModelCriteria::STABLE_DIFFUSSION_XL_1024_FIREWORKS,
                    ProviderCriteria::FIREWORKSAI,
                    CapabilityCriteria::BASIC,
                ],
            ],
            'gemini_2_0_flash' => [
                'provider' => ProviderCriteria::GOOGLE_GEMINI->value,
                'model' => ModelCriteria::GEMINI_2_0_FLASH->value,
                'chat' => true,
                'completion' => false,
                'stream' => true,
                'tools' => false,
                'image_to_text' => true,
                'text_to_image' => false,
                'criteria' => [
                    ModelCriteria::GEMINI_2_0_FLASH,
                    ProviderCriteria::GOOGLE_GEMINI,
                    CapabilityCriteria::SMART,
                ],
            ],
        ];
    }

    private function __construct()
    {
    }
}
